name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  expandable: ^5.0.1

  http: ^0.13.4
  path_provider: ^2.0.8

  json_annotation: ^4.4.0
  file_picker: ^4.5.0
  pin_code_fields: ^7.3.0

  fl_chart: ^0.41.0
  dotted_border: ^2.0.0+2

  flutter_phoenix: ^1.0.0
  bot_toast: ^4.0.1

  bottom_picker: ^1.7.0
  intl: ^0.17.0

  syncfusion_flutter_charts: ^19.4.56
  sizer: ^2.0.15

  fluttertoast: ^8.0.9
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+11
  #  video_player: ^2.3.0
  better_player: ^0.0.81
  video_compress: ^3.1.0
  flutter_quill: ^4.1.0

  cached_network_image: ^3.2.0

  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.4
  timeago: ^3.2.2
  video_thumbnail: ^0.5.0

  flutter_slidable: ^1.2.0
  dio: ^4.0.6


  flutter_rating_bar: ^4.0.0
  video_player: ^2.3.0
  chewie: ^1.3.2

  # network calls
  retrofit: ^3.0.1+1

  # logger
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  #  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  retrofit_generator: 4.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/saluk_logo.png"
  image_path_ios: "assets/images/saluk_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/json/

  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/NeoSansRegular.ttf
        - asset: assets/fonts/NeoSansLight.ttf
          weight: 300
        - asset: assets/fonts/NeoSansMed.ttf
          weight: 400
        - asset: assets/fonts/NeoSansBold.ttf
          weight: 600
        - asset: assets/fonts/NeoSansUltraBold.ttf
          weight: 700
        - asset: assets/fonts/NeoSansBlack.ttf
          weight: 800
